version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: /usr/bin/supervisord
    volumes:
      - ./src:/code
      - ./fixtures:/fixtures
    ports:
      - "8001:80"