version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./config/dockerfiles/postgres/Dockerfile
    ports:
      - "5432:5432"
  redis:
    image: "redis:4.0.10"
    ports:
      - "6379:6379"
  web:
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./src:/code
      - ./fixtures:/fixtures
    ports:
      - "8001:80"
    depends_on:
      - db
      - redis