version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./config/dockerfiles/postgres/Dockerfile
  web:
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/code
    ports:
      - "8000:8000"
    depends_on:
      - db