version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./config/dockerfiles/postgres/Dockerfile
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./src:/code
    ports:
      - "8001:80"
    depends_on:
      - db