version: '3'

services:
  web:
    restart: always
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - ./src:/code
      - ./fixtures:/fixtures
    ports:
      - "80:80"