services:
  web:
    build:
      context: .
      dockerfile: ./config/dockerfiles/web/Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always