# Generated by Django 2.0.4 on 2018-05-31 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
