# Generated by Django 2.0.4 on 2018-06-07 17:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0004_tray'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrayPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tray',
            name='rack',
        ),
        migrations.AddField(
            model_name='grow',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grow',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='identifier',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rack',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='identifier',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='rack',
            name='position_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rack',
            name='position_y',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rack',
            name='position_z',
            field=models.IntegerField(default=0, help_text='The vertical position of the grow in stories. Default is 0for ground or first-floor racks.'),
        ),
        migrations.AddField(
            model_name='tray',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tray',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tray',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tray',
            name='identifier',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='grow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grows.Grow'),
        ),
        migrations.AddField(
            model_name='trayposition',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grows.Rack'),
        ),
        migrations.AddField(
            model_name='trayposition',
            name='tray',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grows.Tray'),
        ),
    ]
