# Generated by Django 2.0.4 on 2018-06-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0005_auto_20180607_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='is_live',
            field=models.BooleanField(default=True, help_text='A live grow has consistent setup and testing procedures,reliable sensor data, regular harvesting and maintenance, etc.A non-live grow is for testing, R&D, or some other sort of grow.'),
        ),
        migrations.AddField(
            model_name='rack',
            name='alphabetical_nickname',
            field=models.CharField(help_text='A memorable nickname for the rack, for quick reference while inside a grow. Reference Six Sigma lab procedures.', max_length=255, null=True),
        ),
    ]
