# Generated by Django 2.0.4 on 2018-06-09 23:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0006_auto_20180609_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Unlisted', 'Unlisted'), ('Public', 'Public')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='grow',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
