# Generated by Django 2.0.4 on 2018-06-09 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grows', '0007_auto_20180609_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
