# Generated by Django 2.0.4 on 2018-07-16 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0008_grow_created_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='grow',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Unlisted', 'Unlisted')], default='Public', max_length=255),
        ),
    ]
