# Generated by Django 2.0.4 on 2018-07-16 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0009_auto_20180716_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='grow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grows.Grow'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('Ambient', 'Ambient')], default='Ambient', max_length=50),
            preserve_default=False,
        ),
    ]
