# Generated by Django 2.0.4 on 2018-07-16 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0012_auto_20180716_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='greengrass_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grow',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_grows', to=settings.AUTH_USER_MODEL),
        ),
    ]
