# Generated by Django 2.0.4 on 2018-07-16 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0013_auto_20180716_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grow',
            old_name='greengrass_arn',
            new_name='greengrass_group_arn',
        ),
        migrations.RenameField(
            model_name='grow',
            old_name='greengrass_id',
            new_name='greengrass_group_id',
        ),
    ]
