# Generated by Django 2.0.4 on 2018-07-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0015_auto_20180717_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
