# Generated by Django 2.0.4 on 2018-07-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0016_grow_greengrass_core_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grow',
            old_name='greengrass_core_arn',
            new_name='greengrass_core_thing_arn',
        ),
        migrations.RenameField(
            model_name='grow',
            old_name='greengrass_core_id',
            new_name='greengrass_core_thing_id',
        ),
        migrations.RenameField(
            model_name='grow',
            old_name='greengrass_core_name',
            new_name='greengrass_core_thing_name',
        ),
    ]
