# Generated by Django 2.0.4 on 2018-07-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0017_auto_20180717_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
