# Generated by Django 2.0.4 on 2018-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0018_auto_20180717_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_certificate_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_certificate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_certificate_keypair_private',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_certificate_keypair_public',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_certificate_pem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
