# Generated by Django 2.0.4 on 2018-07-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0020_auto_20180717_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grow',
            name='greengrass_core_policy_document',
            field=models.TextField(blank=True, null=True),
        ),
    ]
