# Generated by Django 2.0.4 on 2018-07-17 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0021_auto_20180717_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_latest_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grow',
            name='greengrass_core_latest_version_arn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
