# Generated by Django 2.0.4 on 2018-07-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0022_auto_20180717_0307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSGreengrassGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arn', models.CharField(blank=True, max_length=255, null=True)),
                ('group_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_group_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_group_id',
        ),
        migrations.AddField(
            model_name='awsgreengrassgroup',
            name='grow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_greengrass_group', to='grows.Grow'),
        ),
    ]
