# Generated by Django 2.0.4 on 2018-07-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0023_auto_20180717_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSGreengrassCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thing_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('thing_id', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_id', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_pem', models.TextField(blank=True, null=True)),
                ('certificate_keypair_public', models.TextField(blank=True, null=True)),
                ('certificate_keypair_private', models.TextField(blank=True, null=True)),
                ('policy_name', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_arn', models.CharField(blank=True, max_length=255, null=True)),
                ('policy_document', models.TextField(blank=True, null=True)),
                ('policy_version_id', models.CharField(blank=True, max_length=255, null=True)),
                ('arn', models.CharField(blank=True, max_length=255, null=True)),
                ('core_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_version', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_version_arn', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_certificate_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_certificate_id',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_certificate_keypair_private',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_certificate_keypair_public',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_certificate_pem',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_id',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_latest_version',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_latest_version_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_policy_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_policy_document',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_policy_name',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_policy_version_id',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_thing_arn',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_thing_id',
        ),
        migrations.RemoveField(
            model_name='grow',
            name='greengrass_core_thing_name',
        ),
        migrations.AddField(
            model_name='awsgreengrasscore',
            name='grow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_greengrass_core', to='grows.Grow'),
        ),
    ]
