# Generated by Django 2.0.4 on 2018-07-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0025_awsgreengrasscore_has_been_setup'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowSensorPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_archived', models.DateTimeField(blank=True, null=True)),
                ('wifi_network_name', models.CharField(blank=True, max_length=255, null=True)),
                ('grow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='grows.Grow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
