# Generated by Django 2.0.4 on 2018-07-17 18:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0026_growsensorpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='growsensorpreferences',
            name='publish_ssh_key_for_authentication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growsensorpreferences',
            name='sensor_user_password',
            field=models.CharField(blank=True, help_text='Will be auto-generated if left blank.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='growsensorpreferences',
            name='wifi_country_code',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='growsensorpreferences',
            name='wifi_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='growsensorpreferences',
            name='wifi_type',
            field=models.CharField(blank=True, choices=[('WPA/WPA2', 'WPA/WPA2'), ('WEP', 'WEP'), ('Open', 'Open (no password)')], max_length=10, null=True),
        ),
    ]
