# Generated by Django 2.0.4 on 2018-07-17 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0027_auto_20180717_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSGreengrassCoreSetupToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField()),
                ('aws_greengrass_core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_tokens', to='grows.AWSGreengrassCore')),
            ],
        ),
    ]
