# Generated by Django 2.0.4 on 2018-07-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0028_awsgreengrasscoresetuptoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsgreengrasscoresetuptoken',
            name='date_last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
