# Generated by Django 2.0.4 on 2018-09-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0030_awsgreengrasscoresetuptoken_date_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('Relay / Switch', 'Relay / Switch'), ('Ambient', 'Ambient'), ('Outdoor', 'Outdoor'), ('Camera', 'Camera'), ('CO2', 'CO2'), ('pH / EOC', 'pH / EOC'), ('Air Quality', 'Air Quality')], max_length=50),
        ),
    ]
