# Generated by Django 2.0.4 on 2018-09-15 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0031_auto_20180915_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSetupToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField()),
                ('date_last_downloaded', models.DateTimeField(blank=True, null=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='has_been_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensorsetuptoken',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup_tokens', to='grows.Sensor'),
        ),
    ]
