# Generated by Django 2.0.4 on 2018-09-15 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0032_auto_20180915_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('update', models.TextField(null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='grows.Sensor')),
            ],
        ),
    ]
