# Generated by Django 2.0.4 on 2018-09-18 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0033_sensorupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_deactivated', models.DateTimeField(blank=True, null=True)),
                ('date_last_used', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_tokens', to='grows.Sensor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sensorupdate',
            options={'ordering': ['-date_created']},
        ),
    ]
