# Generated by Django 2.0.4 on 2018-09-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0038_relayschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='relayschedule',
            name='action',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=10, null=True),
        ),
    ]
