# Generated by Django 2.0.4 on 2018-09-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0040_relayschedule_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='vpn_config',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='vpn_diagnostics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
