# Generated by Django 2.0.4 on 2018-09-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0041_auto_20180921_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorrelay',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
