# Generated by Django 2.0.4 on 2018-09-21 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0042_sensorrelay_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayScheduleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_new_schedule', models.BooleanField(default=False, help_text='If checked, this item began a new schedule for the relay.')),
                ('date_scheduled', models.DateTimeField(null=True)),
                ('job_id', models.CharField(max_length=30, null=True)),
                ('date_cancelled', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_failed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='relayschedule',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='sensorrelay',
            name='is_enabled',
        ),
        migrations.AddField(
            model_name='relayschedule',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relayscheduleitem',
            name='sensor_relay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='grows.RelaySchedule'),
        ),
    ]
