# Generated by Django 2.0.4 on 2018-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0043_auto_20180921_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayscheduleitem',
            name='job_id',
            field=models.UUIDField(null=True),
        ),
    ]
