# Generated by Django 2.0.4 on 2018-09-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0046_relayscheduleitem_failure_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relayscheduleitem',
            old_name='sensor_relay',
            new_name='relay_schedule',
        ),
    ]
