# Generated by Django 2.0.4 on 2018-09-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0048_auto_20180922_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awsgreengrasscore',
            name='grow',
        ),
        migrations.RemoveField(
            model_name='awsgreengrasscoresetuptoken',
            name='aws_greengrass_core',
        ),
        migrations.RemoveField(
            model_name='awsgreengrassgroup',
            name='grow',
        ),
        migrations.DeleteModel(
            name='AWSGreengrassCore',
        ),
        migrations.DeleteModel(
            name='AWSGreengrassCoreSetupToken',
        ),
        migrations.DeleteModel(
            name='AWSGreengrassGroup',
        ),
    ]
