# Generated by Django 2.0.4 on 2018-10-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0050_remove_relayschedule_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('pin', models.IntegerField()),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='grows.Sensor')),
            ],
        ),
    ]
