# Generated by Django 2.0.4 on 2018-10-28 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0051_sensorswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwitchTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('on_action', models.CharField(choices=[('On', 'On'), ('Off', 'Off')], max_length=10, null=True)),
                ('after_sustained_for_seconds', models.IntegerField(default=0, help_text='If 0, trigger will be executed immediately. Otherwise, must be in position for designated number of seconds.')),
                ('relay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grows.SensorRelay')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='grows.SensorSwitch')),
            ],
        ),
    ]
