# Generated by Django 2.0.4 on 2018-10-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0052_switchtrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='switchtrigger',
            name='identifier',
            field=models.UUIDField(null=True),
        ),
    ]
