# Generated by Django 2.0.4 on 2018-10-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0053_switchtrigger_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchtrigger',
            old_name='relay',
            new_name='trigger_relay',
        ),
    ]
