# Generated by Django 2.0.4 on 2018-10-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0055_remove_sensor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='switchtrigger',
            old_name='on_action',
            new_name='triggered_when_switch_is',
        ),
    ]
