# Generated by Django 2.0.4 on 2018-10-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grows', '0056_auto_20181029_0143'),
        ('salads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('dressings', models.ManyToManyField(blank=True, to='salads.Dressing')),
                ('grow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grows.Grow')),
                ('ingredients', models.ManyToManyField(to='salads.Ingredient')),
                ('microgreens', models.ManyToManyField(to='salads.Microgreen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='salad',
            name='dressings',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='microgreens',
        ),
        migrations.RemoveField(
            model_name='salad',
            name='name',
        ),
        migrations.AddField(
            model_name='salad',
            name='added_dressings',
            field=models.ManyToManyField(blank=True, related_name='added_dressings', to='salads.Dressing'),
        ),
        migrations.AddField(
            model_name='salad',
            name='added_ingredients',
            field=models.ManyToManyField(blank=True, related_name='added_ingredients', to='salads.Ingredient'),
        ),
        migrations.AddField(
            model_name='salad',
            name='added_microgreens',
            field=models.ManyToManyField(blank=True, related_name='added_microgreens', to='salads.Microgreen'),
        ),
        migrations.AddField(
            model_name='salad',
            name='removed_dressings',
            field=models.ManyToManyField(blank=True, related_name='removed_dressings', to='salads.Dressing'),
        ),
        migrations.AddField(
            model_name='salad',
            name='removed_ingredients',
            field=models.ManyToManyField(blank=True, related_name='removed_ingredients', to='salads.Ingredient'),
        ),
        migrations.AddField(
            model_name='salad',
            name='removed_microgreens',
            field=models.ManyToManyField(blank=True, related_name='removed_microgreens', to='salads.Microgreen'),
        ),
        migrations.AddField(
            model_name='salad',
            name='from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salads.SaladTemplate'),
        ),
    ]
