# Generated by Django 2.0.4 on 2018-10-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salads', '0003_auto_20181029_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salads', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='salad',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salads', to='orders.Order'),
        ),
    ]
