# Generated by Django 2.0.4 on 2018-10-29 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salads', '0004_auto_20181029_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaladFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('salad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salads.Salad')),
            ],
        ),
    ]
