# Generated by Django 2.0.4 on 2018-07-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_launchsignup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grow_limit',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
