# Generated by Django 2.0.4 on 2018-08-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180716_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_up_finished',
            field=models.BooleanField(default=True),
        ),
    ]
