# Generated by Django 2.0.4 on 2018-08-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180812_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='date_joined',
            field=models.DateTimeField(),
        ),
    ]
