# Generated by Django 2.0.4 on 2018-10-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
