# Generated by Django 2.0.4 on 2018-10-29 17:16

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_datetime',
            new_name='event_datetime_utc',
        ),
        migrations.AddField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(null=True),
        ),
    ]
