# Generated by Django 2.0.4 on 2018-10-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181029_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_datetime_utc',
        ),
        migrations.AddField(
            model_name='event',
            name='event_end_utc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_utc',
            field=models.DateTimeField(null=True),
        ),
    ]
