# Generated by Django 2.0.4 on 2018-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181029_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end_utc',
            field=models.DateTimeField(null=True, verbose_name='Event end'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_utc',
            field=models.DateTimeField(null=True, verbose_name='Event start'),
        ),
    ]
