"""
Django settings for gardeno project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import requests
from dotenv import load_dotenv

from pathlib import Path  # python3 only

env_path = Path('.') / '.env'
load_dotenv(dotenv_path=env_path)

import os
import boto3

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mc52j)#z-o1q&6s$kf)88e50wdkfn@ds4#0j7m^j-r6)-oyxft'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = os.getenv('ENVIRONMENT') == 'local'
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.humanize',
    'django_countries',
    'timezone_field',
    "django_rq",
    'channels',
    'accounts',
    'grows',
    'safety',
]

if not DEBUG:
    INSTALLED_APPS += 'raven.contrib.django.raven_compat',

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gardeno.urls'

WSGI_APPLICATION = 'gardeno.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gardeno.context_processors.analytics',
                'gardeno.context_processors.globals',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'HOST': os.getenv('DB_HOST'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USERNAME'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'PORT': 5432,
    }
}

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static_src')
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

AUTH_USER_MODEL = 'accounts.User'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '[::1]',
    'gardeno.global',
    '*',
]

RAVEN_CONFIG = {
    'dsn': os.getenv('RAVEN_DSN'),
    # If you are using git, you can also automatically configure the
    # release based on the git info.
    # 'release': raven.fetch_git_sha(os.path.abspath(os.pardir)),
    'release': '0.0.1'
}
GREENGRASS_CLIENT = boto3.client('greengrass')
GREENGRASS_CORE_TYPE_NAME = 'Greengrass_Core'

IOT_CLIENT = boto3.client('iot')

SITE_URL = os.getenv('SITE_URL')

AWS_DEFAULT_REGION = os.getenv('AWS_DEFAULT_REGION')
AWS_IOT_CUSTOM_ENDPOINT = os.getenv('AWS_IOT_CUSTOM_ENDPOINT')

REDIS_HOST = os.getenv('REDIS_HOST')

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, 6379)],
        },
    },
}

ASGI_APPLICATION = "gardeno.routing.application"

JWT_SECRET = os.getenv('JWT_SECRET')
VPN_SECRET_URL = os.getenv('VPN_SECRET_URL')

if not JWT_SECRET:
    print('Missing `JWT_SECRET` from .env file')

RQ_QUEUES = {
    'default': {
        'HOST': REDIS_HOST,
        'PORT': 6379,
        'DB': 0,
        'DEFAULT_TIMEOUT': 360,
    },
}

TIME_INPUT_FORMATS = [
    # Hour, Minute, Second, AM/PM
    '%-I:%M:%S %p',
    '%I:%M:%S %p',
    '%-I:%M:%S%p',
    '%I:%M:%S%p',
    # Hour, Minute, AM/PM
    '%-I:%M %p',
    '%I:%M %p',
    '%-I:%M%p',
    '%I:%M%p',
    # Hour, AM/PM
    '%-I %p',
    '%I %p',
    '%-I%p',
    '%I%p',
    # 24 Hour, Minute, Second
    '%H:%M:%S',
    '%-H:%M:%S',
    # 24 Hour, Minute
    '%H:%M',
    '%-H:%M',
]
