# Generated by Django 2.0.4 on 2018-06-09 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardidentification',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hazardidentification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nearmiss',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='nearmiss',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
